name: CI Frontend

on:
  push:
    branches: [ "test" ]
    paths:
      - frontend/**
  pull_request:
    paths:
      - frontend/**

jobs:
  analysis:
    name: Code Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run Svelte check
        working-directory: frontend
        run: npm run check

      - name: Run tsc check
        working-directory: frontend
        run: npx --yes tsc --noEmit

  unit:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run unit tests
        working-directory: frontend
        run: npx --yes vitest@3.2.4 run --dir src

  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: [ analysis, unit ]

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run integration tests
        working-directory: frontend
        run: npx --yes vitest@3.2.4 run --dir tests/integration

  e2e:
    name: End to End Test
    runs-on: ubuntu-latest
    needs: [ integration ]

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build application
        working-directory: frontend
        run: npm run build

      - name: Install Playwright browsers
        working-directory: frontend
        run: npx --yes playwright install --with-deps chromium

      - name: Run end to end tests
        working-directory: frontend
        run: npx --yes playwright test